name: Sonatype Lifecycle Evaluation

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: "https://finos.sonatype.app/platform"
        username: ${{ secrets.sonatype_user }}
        password: ${{ secrets.sonatype_password }}
        applicationId: morphir-scala
        stage: build
        target: '**/yarn.lock **/package.json'
