name: Sonatype Lifecycle Evaluation

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SonatypeUrl: "https://finos.sonatype.app/platform -D dirExcludes='**/website, **/.*'"
      SonatypeAppId: 'morphir-scala'
      SonatypeStage: 'build'
      SonatypeScanTarget: '*'
      ExcludeDirectory: '-D dirExcludes="**/website, **/.*" **/package.json'
      
    steps:
    - uses: actions/checkout@v1

    - name: TESTING (TEMP)
      run: |
        ls -al
        pwd
    
    - name: Sonatype Lifecycle Software Composition Analysis (SCA) Scan
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        username: ${{ secrets.sonatype_user }}
        password: ${{ secrets.sonatype_password }}
        serverUrl: ${{ env.SonatypeUrl }}
        applicationId: ${{ env.SonatypeAppId }}
        stage: ${{ env.SonatypeStage }}
        target: ${{ env.SonatypeScanTarget }}


    # - name: Retrieve Sonatype SBOM
    #   run: |
    #     iqCredentials=${{ secrets.sonatype_user }}:${{ secrets.sonatype_password }}
    #     echo 'Get internal app ID for '$SonatypeAppId
    #     res=$(curl -u $iqCredentials --location $SonatypeUrl'/api/v2/applications?publicId='$SonatypeAppId)
    #     IFS='"' read -a array <<< "$res"
    #     echo 'Internal app ID: '${array[5]}
    #     internalID=${array[5]}
    #     curl -u $iqCredentials --location $SonatypeUrl'/api/v2/cycloneDx/1.5/'$internalID'/stages/'$SonatypeStage -H 'Accept: application/xml' > Sonatype-SBOM.xml
    #     echo 'Sonatype SBOM: '
    #     cat Sonatype-SBOM.xml

