name: Sonatype Lifecycle Evaluation

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SonatypeUrl: https://finos.sonatype.app/platform
      SonatypeAppId: morphir-scala
      SonatypeStage: Build
      SonatypeScanTarget: '**/yarn.lock **/package.json'
      

    steps:
    - uses: actions/checkout@v1
    
    - name: Sonatype Lifecycle Software Composition Analysis (SCA) Scan
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: $env.SonatypeURL
        username: ${{ secrets.sonatype_user }}
        password: ${{ secrets.sonatype_password }}
        applicationId: $env.SonatypeAppId
        stage: Build
        target: $env.SonatypeScanTarget


    - name: Retrieve Sonatype SBOM
      run: |
         echo "TBD: Trigger API Call"
